### ISSUE TITLE
Deadlock after being hit by an arrow while wearing terra protection amulet

### ISSUE THREAD

**Issue by Dimanesson** [Frostygames0/elemental-amulets#2]
After a few arrow hits the game completely freezes in a deadlock. See the error report below
[crash-2021-09-24_22.27.53-server.txt](https://github.com/Frostygames0/Elemental-Amulets/files/7228035/crash-2021-09-24_22.27.53-server.txt)

**Comment by Frostygames0** [comment]
Thanks for the report! I’m trying to fix this and other bugs now.

**Comment by Frostygames0** [comment]
Hm… I tried to reproduce bug but everything works fine.
What mods do you use? The report mentions Perfomant and Quark. 
Try running the game without them and check if bug persists.

Also provide logs/debug.log

**Comment by Frostygames0** [comment]
https://www.curseforge.com/minecraft/mc-mods/elemental-amulets/files/3472215
Also after that, try this version with mods
and try setting max-tick-time to -1 if you're on the server.

**Comment by Dimanesson** [comment]
> https://www.curseforge.com/minecraft/mc-mods/elemental-amulets/files/3472215
> Also after that, try this version with mods

That worked for me. Thank you!

**Comment by Frostygames0** [comment]
> That worked for me. Thank you!

It's nice to hear that!
if you have any other problems with the mod, please let me know! :)
